name: mlops_e2e_py310

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.11
  - pip==23.1.2
  - numpy==1.25.1
  - pandas==2.0.3
  - pytest==7.4.0
  - pip:
      - azureml-sdk==1.52.0
      - azureml-defaults==1.52.0
      - azureml-monitoring
      - black==23.7.0
      - cached-property==1.5.2
      - jsonlines==3.1.0
      - nteract-scrapbook==0.4.2
      - pydocumentdb==2.3.5
      - tqdm==4.65.0
      - pyemd==1.0.0
      - ipywebrtc==0.6.0
      - pre-commit==3.3.3
      - scikit-learn==1.3.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - regex==2023.6.3
      - seaborn
      - joblib
